### PR TITLE
Bugfix for repeater list extension returning wrong rowData object in rowRenderer callback.

### LINKED ISSUE #1075: Repeater: list_rowRendered issue
The helpers object that is passed into custom row renderer function has changed with #1022 .

Previously, `helpers.rowData` was an object that represented the current row.  Now it is an array that represents *all* rows.

Previously:
screenshot 2015-02-10 18 28 14

Currently:
screenshot 2015-02-10 18 28 39

### PR DESCRIPTION
**Pull request by futuremint**
Adds unit tests to both list callbacks to verify the shape of the rowData object now.
Fixes #1075.

### CODE REVIEW

File: js/repeater-list.js [hunk 1]
```diff
@@ -379,7 +379,7 @@
 			this.viewOptions.list_rowRendered({
 				container: $tbody,
 				item: $row,
-				rowData: data
+				rowData: data.items[index]
```
Comment (kevinparkerson) [inline js/repeater-list.js]: this can be simplified to just `subset[index]`  I was already passing in the correct "items" array as the subset, I just mistakingly put the wrong argument there >.<

**Comment by kevinparkerson** [comment]
Nice catch!!!

File: js/repeater-list.js (hunk 1 above)
Comment (cormacmccarthy) [inline js/repeater-list.js]: what even _is_ subset? That variable name needs to change...

Comment (kevinparkerson) [inline js/repeater-list.js]: These docs will change soon, but: http://getfuelux.com/extensions.html#writing-extensions-repeater-helpers

It's the "subset" of information that is being iterated over. In this case, data.items. `renderRow` is called passing the `helpers.subset` value as the `subset` argument. I suppose it could be renamed "items" in the scope of the `renderRow` function...

Comment (cormacmccarthy) [inline js/repeater-list.js]: Is there any case where it isn't just a convenience accessor for the data.items param?
